In [11]:
import pandas as pd
import numpy as np

data=pd.read_csv("../csv-files/customer_shopping_behavior.csv");
data.head(5)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [12]:
data.info()
data.isnull().sum()

data['Review Rating'] = data['Review Rating'].fillna(
    data.groupby('Category')['Review Rating'].transform('median')
)
print(data.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB
Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [13]:
#making columns as lowercase and replacing space with underscore
data.columns=data.columns.str.lower()
data.columns=data.columns.str.replace(' ','_')
data=data.rename(columns={'purchase_amount_(usd)':'purchase_amount'})
data.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [14]:
#create a column for age_group

labels=['Young Adult','Adult','Middle-aged','Senior']
data['age_group']=pd.qcut(data['age'],q=4,labels=labels)
data[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [15]:
#create column purchase_frequency_days

frequent_mapping={
    'Fortnightly':14,
    'Weekly':10,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90
}
data['purchase_frequent_days']=data['frequency_of_purchases'].map(frequent_mapping)
data[['frequency_of_purchases','purchase_frequent_days']].head(10)

  frequency_of_purchases  purchase_frequent_days
0            Fortnightly                      14
1            Fortnightly                      14
2                 Weekly                      10
3                 Weekly                      10
4               Annually                     365
5                 Weekly                      10
6              Quarterly                      90
7                 Weekly                      10
8               Annually                     365
9              Quarterly                      90

In [22]:
#promo_code_used and discount_appilend have same values
# (data['discount_applied']==data['promo_code_used']).all()
# data=data.drop('promo_code_used',axis=1)
# data.columns
data.to_csv('cleaned_customer_shopping.csv',index=False)

In [ ]:
from sqlalchemy import create_engine

# MySQL connection
engine = create_engine("mysql+mysqlconnector://root:Karthik%4020@localhost:3306/customer_analysis")
cleaned_data=pd.read_csv('../csv-files/cleaned_customer_shopping.csv')
cleaned_data.to_sql(name='customer_shopping_behaviour', con=engine, if_exists='replace', index=False)

SyntaxError: source code string cannot contain null bytes (<string>)